services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    ports:
      - "8081:8081"
    volumes:
      - ./:/var/www/symfony
  db:
    image: library/mysql:8.0.35
    command: [ "--default-authentication-plugin=mysql_native_password", "--max-allowed-packet=32505856" ]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "demo"
      MYSQL_DATABASE: "demo"
      MYSQL_USER: "demos"
      MYSQL_PASSWORD: "demos"
    volumes:
      - db-volume:/var/lib/mysql
    deploy:
      resources:
        reservations:
          memory: 2gb
volumes:
  db-volume:

